import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  registrationContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ecf0f1",
    justifyContent: "flex-end",
    paddingBottom: 30,
    //   width: "100%",
    //   height: "100%",
    //   justifyContent: "flex-end",
  },
  contentWrapper: {
    paddingHorizontal: 16,
    width: "100%",
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: 32,
    position: "relative",
  },
  avatarContainer: {
    // top: "-50%",
    // left: "50%",
    // transform: [{ translateX: -50 }, { translateY: -50 }],
    // width: 120,
    // height: 120,
    position: "absolute",
  },

  avatar: {
    position: "absolute",
    top: -92,
    left: "50%",
    transform: [{ translateX: -60 }, { translateY: -60 }],
    width: 120,
    height: 120,

    borderRadius: 16,
  },
  addImageBtn: {
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    right: 0,
    bottom: 14,
    transform: [{ translateX: 12 }],
    zIndex: 1,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#FF6C00",
    color: "#FF6C00",
  },
  addBtnIcon: {
    width: "60%",
    height: "60%",
  },
  registrationHeaderTitle: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: 30,
    lineHeight: 35,
    textAlign: "center",
    marginTop: 32,
    marginBottom: 32,
    color: "#212121",
  },
  input: {
    height: 50,
    fontSize: 16,
    padding: 16,
    marginBottom: 16,

    color: "#212121",
    backgroundColor: "#f6f6f6",

    borderWidth: 1,
    borderColor: "#e8e8e8",
    borderRadius: 8,
  },
  text: {
    color: "white",
    fontSize: 42,
    lineHeight: 84,
    fontWeight: "bold",
    textAlign: "center",
    backgroundColor: "#000000c0",
  },
  inputPasswordWraper: {
    position: "relative",
  },
  passwordShowText: {
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
    color: "#1B4371",
  },
  passwordShowButton: {
    position: "absolute",
    top: 16,
    right: 16,
  },
  registerButton: {
    display: "flex",
    width: 343,
    paddingHorizontal: 16,
    paddingVertical: 32,

    flexDirection: "column",
    alignItems: "center",
    gap: 12,
    borderRadius: 100,
    backgroundColor: "#FF6C00",
  },
  registerButtonText: {
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
    color: "#fff",
  },
});
export const {
  registrationContainer,
  contentWrapper,
  avatarContainer,
  avatar,
  addImageBtn,
  addBtnIcon,
  registrationHeaderTitle,
  input,
  text,
  inputPasswordWraper,
  passwordShowText,
  passwordShowButton,
  registerButton,
  registerButtonText,
} = styles;
